package com.peihou.willgood2.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.peihou.willgood2.pojo.LinkedType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LINKED_TYPE".
*/
public class LinkedTypeDao extends AbstractDao<LinkedType, Long> {

    public static final String TABLENAME = "LINKED_TYPE";

    /**
     * Properties of entity LinkedType.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MacAddress = new Property(1, String.class, "macAddress", false, "MAC_ADDRESS");
        public final static Property Type = new Property(2, int.class, "type", false, "TYPE");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
        public final static Property McuVersion = new Property(4, int.class, "mcuVersion", false, "MCU_VERSION");
        public final static Property State = new Property(5, int.class, "state", false, "STATE");
    }


    public LinkedTypeDao(DaoConfig config) {
        super(config);
    }
    
    public LinkedTypeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LINKED_TYPE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"MAC_ADDRESS\" TEXT," + // 1: macAddress
                "\"TYPE\" INTEGER NOT NULL ," + // 2: type
                "\"NAME\" TEXT," + // 3: name
                "\"MCU_VERSION\" INTEGER NOT NULL ," + // 4: mcuVersion
                "\"STATE\" INTEGER NOT NULL );"); // 5: state
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LINKED_TYPE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, LinkedType entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String macAddress = entity.getMacAddress();
        if (macAddress != null) {
            stmt.bindString(2, macAddress);
        }
        stmt.bindLong(3, entity.getType());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
        stmt.bindLong(5, entity.getMcuVersion());
        stmt.bindLong(6, entity.getState());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, LinkedType entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String macAddress = entity.getMacAddress();
        if (macAddress != null) {
            stmt.bindString(2, macAddress);
        }
        stmt.bindLong(3, entity.getType());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
        stmt.bindLong(5, entity.getMcuVersion());
        stmt.bindLong(6, entity.getState());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public LinkedType readEntity(Cursor cursor, int offset) {
        LinkedType entity = new LinkedType( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // macAddress
            cursor.getInt(offset + 2), // type
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // name
            cursor.getInt(offset + 4), // mcuVersion
            cursor.getInt(offset + 5) // state
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, LinkedType entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMacAddress(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setType(cursor.getInt(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMcuVersion(cursor.getInt(offset + 4));
        entity.setState(cursor.getInt(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(LinkedType entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(LinkedType entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(LinkedType entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
